# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [dev]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.15.1
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  cache: 'pnpm'
            - run: pnpm install
            - run: pnpm format
            - run: pnpm build
            - run: pnpm coverage
            - run: |
                  git config user.name ksenginew
                  git config user.email ksenginew@users.noreply.github.com
                  git add .
                  git add -f ./dist
                  git commit -m "generated"
                  git push
